### ISSUE TITLE
Moving to the OrgManager org

### ISSUE THREAD

**Issue by m1guelpf** [orgmanager/node-orgmanager-api#2]
@TiagoDanin To move this to the org:
- Under settings, transfer the repo to the org

Then,  I'll create a node mantainers team and add you

**Comment by m1guelpf** [comment]
I've given you the privileges required

**Comment by m1guelpf** [comment]
Also, I've created an OrgManager org on npm and invited you

**Comment by TiagoDanin** [comment]
😔 Unfortunately the NPM does not allow delete or move the package.
Solution: Create a new package name
My NPM user: https://www.npmjs.com/~tiagodanin

**Comment by m1guelpf** [comment]
@TiagoDanin But as we now have a npm org, we can scope the package, so that should fix it
